export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const UPDATE_ERROR = 'UPDATE_ERROR';
export const DELETE_ERROR = 'DELETE_ERROR';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const GET_CONTACT = 'GET_CONTACT';
export const CLEAR_CONTACTS = 'CLEAR_CONTACTS';
export const GET_ERROR = 'GET_ERROR';

export const SEARCH_CONTACTS = 'SEARCH_CONTACTS';
// export const SEARCH_CONTACTS = 'SEARCH_CONTACTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const CURRENT_CONTACT = 'CURRENT_CONTACT';
export const CONTACT_ERROR = 'CONTACT_ERROR';
export const CLEAR_ERROR_CONTACTS='CLEAR_ERROR_CONTACTS'

// export const USER_LOADED = 'USER_LOADED';
export const LOADED_ERROR = 'LOAD_ERROR';
export const LOADED_USERS = 'LOAD_USERS';
export const REG_DATA = 'REGDATA';
export const LOGIN_DATA = 'LOGIN_DATA';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REG_SUCCESS = 'REG_SUCCESS';
export const REG_FAIL = 'REG_FAIL';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT= 'LOGOUT';
export const LOGIN= 'LOGIN';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
